#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo rm /var/www/html/index.nginx-debian.html

# testing nginx configurations
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
